apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: example-workspace
spec:
  forProvider:
    source: Inline
    module: |
      provider "aws" {
        region = "us-east-2"
        alias = "alternative"  
      }

      resource "random_pet" "this" {
        length = 2
      }

      locals {
        bucket_name = "s3-bucket-${random_pet.this.id}"
      }

      resource "aws_s3_bucket" "example_bucket" {
        bucket = local.bucket_name
        acl    = "private"

        versioning {
          enabled    = true
          mfa_delete = false
        }

        object_lock_configuration {
          object_lock_enabled = true

          rule {
            default_retention {
              mode  = "GOVERNANCE"
              days  = 1
            }
          }
        }

        lifecycle_rule {
          id      = "simple-rule"
          enabled = true

          expiration {
            days = 90
          }

          noncurrent_version_expiration {
            days = 30
          }
        }
      }

      output "bucket_name" {
        value = aws_s3_bucket.example_bucket.bucket
      }

      output "bucket_arn" {
        value = aws_s3_bucket.example_bucket.arn
      }

  providerConfigRef:
    name: aws-provider-config  